version: 3
services:
  message-broker:
    container_name: rabbit-mq
    image: rabbitmq:alpine
    # Apro la porta temporaneamente perché al momento non sono containerizzati i microservizi
    ports:
      - "5672:5672"
  db-dashboards:
    container_name: db-dashboards
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db-dashboards:/var/lib/postgresql/data
  db-events:
    container_name: db-events
    image: postgres:alpine

    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - db-events:/var/lib/postgresql/data
  db-transactions:
    container_name: db-transactions
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - db-transactions:/var/lib/postgresql/data
  db-users:
    container_name: db-users
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    volumes:
      - db-users:/var/lib/postgresql/data
volumes:
  db-dashboards:
  db-events:
  db-transactions:
  db-users: