apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8762"
      port: 8762
      targetPort: 8762
  selector:
    io.kompose.service: api-gateway
status:
  loadBalancer: {}
