apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db-events
  name: db-events
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: db-events
status:
  loadBalancer: {}
