apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db-transactions
  name: db-transactions
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5432
  selector:
    io.kompose.service: db-transactions
status:
  loadBalancer: {}
