apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db-users
  name: db-users
spec:
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5432
  selector:
    io.kompose.service: db-users
status:
  loadBalancer: {}
