apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: message-broker
  name: message-broker
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: message-broker
status:
  loadBalancer: {}
