apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: service-discovery
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-discovery
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: service-discovery
    spec:
      containers:
        - image: service-discovery
          name: eureka-server
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
status: {}
