spring:
  application:
    name: events
  datasource:
    url: jdbc:postgres://db-events:5433
    username: postgres
    password: 1234

server:
  port: 8031

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

---
spring:
  profiles: docker

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
