spring:
  application:
    name: transactions
  datasource:
#    url=jdbc:h2:mem:testdb
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    url: jdbc:postgres://db-transactions:5434
#    username: postgres
#    password: 1234

server:
  port: 8011

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

---
spring:
  profiles: docker

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
